name: process-notebooks
description: 'Run processing of notebooks'
inputs:
  run_all:
    description: 'run all notebooks or only changed'
    required: true
    type: string
  exec_flag:
    description: 'flag for execution'
    required: true
    type: string
  exercise-continue-on-error:
    description: 'Should continue on Error in exercices'
    required: false
    default: false
    type: string

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Get commit message
      run: |
        readonly local msg=$(git log -1 --pretty=format:"%s")
        echo "COMMIT_MESSAGE=$msg" >> $GITHUB_ENV
      shell: bash -l {0}

    - name: Setup
      uses: ./.github/actions/setup
      with:
        force_env_update: 'false'

    # - name: Get changed files
    #   if: ${{ inputs.runall != 'true' }}
    #   id: changes
    #   uses: trilom/file-changes-action@v1.2.4
    #   with:
    #     output: " "

    - name: Get notebooks
      run: |
        if ${{ inputs.run_all == 'true' }}; then
          # nbs="tutorials/*/*Tutorial*.ipynb";
          nbs="tutorials/W2D5_*/*Tutorial*.ipynb";
        else
          nbs=`python ci/select_notebooks.py ${{ steps.changes.outputs.files }}`;
        fi
        echo "NBS=$nbs" >> $GITHUB_ENV
      shell: bash -l {0}

    - name: Install XKCD fonts
      run: |
        sudo apt-get update -yq
        sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
        sudo apt-get install msttcorefonts -qq
        rm -f $HOME/.matplotlib/fontList.cache
      shell: bash -l {0}

    # - name: Install C++ compiler in conda environment
    #   run: conda install -c conda-forge gxx_linux-64
    #   shell: bash -l {0}
    # # Necessary for SDFC to work
    # - name: Install eigen/SDFC
    #   run: |
    #     sudo apt-get install -y libeigen3-dev
    #     echo "CC=gcc-9" >> $GITHUB_ENV
    #     echo "CXX=g++-9" >> $GITHUB_ENV
    #     echo "/usr/bin/gcc-9" >> $GITHUB_PATH
    #     echo "/usr/bin/g++-9" >> $GITHUB_PATH
    #     git clone https://github.com/yrobink/SDFC-python.git
    #     cd SDFC-python
    #     pip install pybind11
    #     python setup.py install
    #     pip show SDFC
    #     cd ..
    #   shell: bash -l {0}

    - name: Process notebooks
      id: process_notebooks
      if: ${{ env.NBS != '' }}
      run: |
        python ci/process_notebooks.py ${{ env.NBS }} ${{ inputs.exec_flag}}
      shell: bash -l {0}

    - name: verify exercises
      # continue-on-error: ${{ inputs.exercise-continue-on-error }}
      continue-on-error: ${{ true }}
      if: ${{ env.NBS != '' }}
      id: verify_exercises
      run: |
        pip install fuzzywuzzy
        python ci/verify_exercises.py ${{ env.NBS }} --c "$COMMIT_MESSAGE"
      shell: bash -l {0}

    - name: make PR comment notebooks
      id: pr_comment
      if: ${{ env.NBS != '' }}
      run: |
        branch=${{ github.event.pull_request.head.ref }}
        python ci/make_pr_comment.py ${{ env.NBS }} --branch $branch --o comment.txt
      shell: bash -l {0}
